### ISSUE TITLE
ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by prubbens** [eyurtsev/fcsparser#3]
I get the following error parsing a .fcs. I have parsed a dozen of files before, never got the above error. It is due from the function `read_data`: `data = data.reshape((num_events, num_pars)). ` Any idea where this might be coming from? I can send you the .fcs file if needed.

**Comment by eyurtsev** [comment]
My extremely naive guess is that the fcs file is corrupt, but can't tell for sure without more information. Could you attach the `.fcs` file, include the full stack trace and versions of fcsparser, numpy, scipy and pandas?

**Comment by prubbens** [comment]
Thought so too, which is why in the meanwhile I have asked the experimentator to look at the file also. 
[C08 99  t2 5000x.fcs.zip](https://github.com/eyurtsev/fcsparser/files/383956/C08.99.t2.5000x.fcs.zip)

Traceback (most recent call last):

`
  File "<ipython-input-17-38ab60764f46>", line 1, in <module>
    runfile('/home/prubbens/dir/importdata.py', wdir='/home/prubbens/dir')

  File "/home/prubbens/anaconda3/lib/python3.4/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/home/prubbens/anaconda3/lib/python3.4/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "/home/prubbens/prubbens/dir/importdata.py", line 16, in <module>
    meta, data = fcsparser.parse(dummystring, meta_data_only=False, reformat_meta=True)

  File "/home/prubbens/anaconda3/lib/python3.4/site-packages/fcsparser/api.py", line 484, in parse
    parsed_fcs = FCSParser(path, read_data=read_data, channel_naming=channel_naming)

  File "/home/prubbens/anaconda3/lib/python3.4/site-packages/fcsparser/api.py", line 111, in __init__
    self.read_data(f)

  File "/home/prubbens/anaconda3/lib/python3.4/site-packages/fcsparser/api.py", line 361, in read_data
    data = data.reshape((num_events, num_pars))`

ValueError: total size of new array must be unchanged

Versions: 
fcsparser: 0.1.1
numpy: 1.11.0
scipy: 0.16.1
pandas: 0.18.0

**Comment by prubbens** [comment]
All other .fcs files were parsed fine.

**Comment by prubbens** [comment]
Apparently a corrupt file, updated version works fine. Sorry to trouble you.

**Comment by eyurtsev** [comment]
Sounds good! Good luck with the science :)
